
INSERT INTO CHAT_USER (USER_NAME, PASSWORD) VALUES ('user123','passwd');
INSERT INTO CHAT_USER (USER_NAME, PASSWORD) VALUES ('woman1','passwd');
INSERT INTO CHAT_USER (USER_NAME, PASSWORD) VALUES ('dev91','passwd');

INSERT INTO CHAT_ROLE (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO CHAT_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO CHAT_USER_ROLE (USER_ID, ROLE_ID) VALUES (2,1);
INSERT INTO CHAT_USER_ROLE (USER_ID, ROLE_ID) VALUES (3,1);

INSERT INTO CHAT_MESSAGE (MESSAGE_TEXT, MESSAGE_DATE, USER_ID) 
	VALUES ('Hello','21-06-2017 21:00:00',1);
INSERT INTO CHAT_MESSAGE (MESSAGE_TEXT, MESSAGE_DATE, USER_ID) 
	VALUES ('Hi','21-06-2017 21:38:00',2);
INSERT INTO CHAT_MESSAGE (MESSAGE_TEXT, MESSAGE_DATE, USER_ID) 
	VALUES ('How are you?','21-06-2017 21:50:00',1);